### PR TITLE
feat: added fixed header to the table

### LINKED ISSUE #453: feat: add new feature to the table component
Requirements:
-The table header should be fixed in the top
-The user should  resize the columns
-The user should make the soring in the table

### PR DESCRIPTION
**Pull request by AlejandroYanes**
fixes #453

### CODE REVIEW

File: src/components/Table/head/index.js [hunk 1]
```diff
@@ -30,20 +30,34 @@ export default function Head(props) {
...
+        }
+        return defaultSortDirection;
+    };
+
+    const isSelected = (field) => {
+        if (field) {
+            return field === selectedColumn;
+        }
+        return false;
+    };
```
Comment (LeandroTorresSicilia) [inline src/components/Table/head/index.js]: you can put this function outside
same for resolveSortDirection

File: src/components/Table/index.js [hunk 2]
```diff
@@ -79,48 +84,70 @@ export default class Table extends Component {
     }
 
     handleColumnSelect(event, columnIndex) {
-        const { onSort } = this.props;
+        const { onSort, sortBy, sortDirection } = this.props;
         const { columns } = this.state;
         const { field } = columns[columnIndex];
-        onSort(event, field);
-        this.setState({ selectedColumn: columnIndex });
+        let newSortDirection;
```
Comment (LeandroTorresSicilia) [inline src/components/Table/index.js]: nextSortDirection
