### PR TITLE
fix: fixed overview section

### LINKED ISSUE #378: fix: change the overview page

### PR DESCRIPTION
**Pull request by TahimiLeonBravo**
fixes #378

### CODE REVIEW

**Comment by LeandroTorresSicilia** [comment]
follow conventional commit
fix: fixed overview section

File: library/pages/components/FeatureList/item.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import classnames from 'classnames';
+import './styles.css';
```
Comment (LeandroTorresSicilia) [inline library/pages/components/FeatureList/item.js]: only needed in index

File: src/components/Accordion/readme.md [hunk 2]
```diff
@@ -1,3 +1,8 @@
+##### accordion base
+
+    <FeatureList />
```
Comment (LeandroTorresSicilia) [inline src/components/Accordion/readme.md]: here in the accordion examples?
